### ISSUE TITLE
title/name

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-components#1]
Please:
* Skim the [document content](https://www.w3.org/WAI/intro/components.php)
* Skim the [requirements](https://www.w3.org/WAI/EO/changelogs/cl-components#requirements)
* Read and think about previous discussions on the title:
** [e-mail thread](https://lists.w3.org/Archives/Public/w3c-wai-eo/2005JanMar/0104.html) - click "Next in thread" to see more
** [minutes 1](https://www.w3.org/2005/02/04-eo-minutes#item03)
** [minutes 2](https://www.w3.org/2005/02/11-eo-minutes#item02)
* See where it is in the [draft navigation](https://w3c.github.io/wai-website-components/components/preview/example-home) &mdash; under "Accessibility Fundamentals" and "Standards/Guidelines" - with placeholder renaming <s>"How Accessibility Works"</s> _update:_ How Standards Work Together

Please comment on:
* pros, cons, considerations of "Essential Components of Web Accessibility"
* pros, cons, considerations of <s>"How Accessibility Works"</s> _update:_ How Standards Work Together

Please add other brainstorms, along with pros, cons, considerations for them...

**Comment by yatil** [comment]
My gut feeling:

Move to Standards & Guidelines and rename to How Standards Work Together, integrate a teaser/link to this document into the Accessibility Intro.

**Comment by bakkenb** [comment]
I do not particularly like "How Accessibility Works" as it is too general and could be about any number of topics.

**Comment by bakkenb** [comment]
Please read [renaming discussion from 01 September 2017 Meeting](https://www.w3.org/2017/09/01-eo-minutes.html#item02) prior to adding more to this thread.

**Comment by shawna-slh** [comment]
Note the current plan is to add a little [up front about standards](https://github.com/w3c/wai-components/issues/4), and add a little [about WAI-ARIA](https://github.com/w3c/wai-components/issues/2).

**Comment by sharronrush** [comment]
There was mention in the meeting of a phrase along the lines of "Accessibility Ecosystem." I like that something along the lines of that title also allows a bit of the additional points that are made about users and their environments. The peripheral mentions of contributing factors beyond the standards. That was one reason I thought "How Accessibility Works" was also OK even if broad.

**Comment by dboudreau** [comment]
I prefer "Essential components" to "How accessibility works". I appreciate that we're trying to make the language simpler, but changing the title of the resource alone would do very little towards achieving that goal. The content of the document is still complex, it refers to a lot of complicated concepts, and I guess I don't really like the idea of claiming that this is how thing thing works... In a way, I've been doing this for over 17 years, and oftentimes, I still feel like I don't know how accessibility works... I also agree with Brent that it's a pretty bold/broad statement.

**Comment by iamjolly** [comment]
I really like the suggestion of "How Standards Work Together" from @yatil's [comment earlier on this issue](https://github.com/w3c/wai-components/issues/1#issuecomment-324920704).

**Comment by nitedog** [comment]
I don't feel too strongly but I think "how standards work together" is too generic, even if it is within the WAI website. I think this page is also used outside the context of the WAI website to explain how the different components work together. Here are some brainstorms:

- Web Accessibility Standards
- Components of Web Accessibility
- Technical View on Web Accessibility
- Standards for Web Accessibility
- Making Web Accessibility Work
- Web Accessibility Ecosystem

I prefer the focus on "components", "ecosystem", or such rather than on standards and guidelines, because these change. For example, parts of ATAG, UAAG, and WCAG may be rolled in together in future guidelines, and also ARIA is increasingly integrated into HTML (even if it may continue to exist for other purposes beyond HTML).

**Comment by shawna-slh** [comment]
One thing to keep in mind is that we can have a shortened title in the navigation and a longer title &/or subtitle for the doc. For example, could have doc title "How Web Accessibility Standards Work Together", and in the nav shortened "How Standards Work Together".

**Comment by shawna-slh** [comment]
< joke >
/me looks up "ecosystem" . . . "a community of living organisms in conjunction with the nonliving components of their environment (things like air, water and mineral soil), interacting as a system."
/me refrains from commenting about which components are living and nonliving ;-)
< /joke >

Seriously though: While I kinda like the idea of "ecosystem", it seems too much of a stretch. I played with thesaurus and didn't come up with anything better.

**Comment by shawna-slh** [comment]
Eric says in [survey](https://www.w3.org/2002/09/wbs/35532/EO-Weekly-1-Sep-2017/results#xq2):

> I think we need to be practical with this and move on. If there is no clear advantage of renaming a resource in a certain way, we should leave as is and put our energy to work on the content of documents.

**Comment by shawna-slh** [comment]
Another idea:
Title: **Components of Web Accessibility: Standards, Tools, People**
Nav: "Standards/Guidelines" > "**Components: Standards, Tools, People**"

**Comment by bakkenb** [comment]
I don't like "How Standards Work Together." The page is about more than that. 

I am leaning more strongly to leaving the title as is. Also, if left as is, I don't think we can shorten the title in the navigation either. I don't think "Essential Components" by itself works well at all under the Standards/Guidelines top nav category.

+1 to Eric

**Comment by nrhsinclair** [comment]
Ecosystem is a little "jargony"
This may be cheesy, but something along the lines:
Standards, Design, and Development: Bringing It All Together
Standards, Design, and Development: Essential Components

**Comment by shawna-slh** [comment]
+1 to @nrhsinclair that Ecosystem is a little "jargony"
(that's what I was thinking but didn't write down. :-)

@nrhsinclair - thoughts on how to include the people aspect?

**Comment by iamjolly** [comment]
I think "system" instead of "ecosystem" might work better. Might be more direct. Although it also might not make folks think about the people aspect. 

I found this definition which seems to apply here:
> A system is a group of interrelated, interacting, or interdependent parts that form a complex whole.

So, maybe something like:
- Essential Components of Accessible Systems
- Accessible Systems: People, Standards, and Tools
- Interdependent Co-Arising: Accessibility Enlightenment for the 21st Century ;)

(Sorry for that last one!)

**Comment by hkramer** [comment]
I like "Essential Components of Accessible Systems" 
I like Eric's proposed title but I don't think it fits the document.
-1 to Shawn's and nrhsinclair's suggestions - too lumbering.

**Comment by yatil** [comment]
-0.3 to “Essential Components of Accessible Systems” as this is inside the “Standards & Guidelines” section of the navigation and therefore should be “Essential Components of the Accessible System as designed and supported by W3C Standards & Guidelines”. I don’t think it is necessarily saying a lot about how accessibility works in other systems.

All in all, I have no further ideas and let the group decide. I think any name is fine and there doesn’t seem to be a clear upside of picking one over the other, so I could even live with the original title.

**Comment by vmmiller** [comment]
@nitedog > +1 to any of below:
Web Accessibility Standards
Components of Web Accessibility
Making Web Accessibility Work

**Comment by shawna-slh** [comment]
-1 to "Essential Components of Accessible Systems" because sounds to me like a technical system, like an IT solutions package.

also, agree with @iamjolly that "systems" leaves out the people aspect.

**Comment by sharronrush** [comment]
No change to title of this resourcehttps://www.w3.org/2017/09/08-eo-minutes.html#ResolutionSummary
