### ISSUE TITLE
fix colors to avoid relationship confusion

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-components#27]
Fix color that implies relationships that are not correct:
* HTML, ARIA, CSS are on blue background. SVG, SMIL, ETC. are on orange background. They shouldn't be on either.
* ATAG and WCAG are blue. UAAG is orange.

![image](https://github.com/w3c/wai-components/assets/6991814/cc8ce7b5-013f-4dc5-934f-d0a2dc1a4a0e)

**Comment by zwiastunsw** [comment]
@shawna-slh:
I made Polish versions of the graphics in SVG. Maybe they can help to solve this problem?
See #34
