### ISSUE TITLE
Use of the word "developers" in the introduction

### ISSUE THREAD

**Issue by dboudreau** [w3c/wai-components#3]
**Criticality:** low
**Priority:** low

The introduction section refers to the various components, and refers to anyone who has a role to play in web content as developers.

> developers - designers, coders, authors, etc., including developers with disabilities and users who contribute content

I have a problem with referring to everyone who has a role to play in web content as a developer, whether they're an actual developer, a content writer, a designer, a tester, or whatnot. I think it might give people the wrong idea about who we have in mind... Why not use another qualifier instead, such as web stakeholders, or web resources, even?

**Comment by shawna-slh** [comment]
Thanks for the input. Let's brainstorm ideas....

**Comment by shawna-slh** [comment]
In context of the [introduction](https://w3c.github.io/wai-website/standards/web-accessibility-components/#intro):

>* **content** - the information in a Web page or Web application, including: ...
>* **Web browsers, media players**, and other “user agents”
assistive technology, in some cases - screen readers, alternative keyboards, switches, scanning software, etc.
>* **users**’ knowledge, experiences, and in some cases, adaptive strategies using the Web
>* **developers** - designers, coders, authors, etc., including developers with disabilities and users who contribute content
>* **authoring tools** - software that creates Web sites
>* **evaluation tools** - Web accessibility evaluation tools, HTML validators, CSS validators, etc.

**Comment by shawna-slh** [comment]
What about "creators" ?

Sometimes use "authors", although to be that seems too much like just writers.

**Comment by shawna-slh** [comment]
I started to change it to "content creators"... then realized that "developers" is used throughout the document. I think it would be awkward to change it to "content creators" everywhere.

It doesn't see that "web stakeholders" or "web resources" would work to replace "developers" through the document either.

Maybe it's OK as is in this one document?

I'm happy to consider other ideas. Feel free to re-open if you have other ideas after reading through the document and seeing how we use "developers".
