### ISSUE TITLE
Redundant section in wai-components-example.md

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wai-components#35]
The "Components and Guidelines Illustration Description" section in the document **Descriptions of Essential Components of Web Accessibility Illustrations** is redundant. The image is already described in the first section "How the Components Relate Illustration Description"

**Comment by remibetin** [comment]
@zwiastunsw We have fixed this, see https://www.w3.org/WAI/fundamentals/components/examples/

Thanks!
